export const INIT = 'init'
export const STARTED = 'started'
export const CHOSE_1 = 'choose your lang'
export const CHOSE_2 = 'choose preference lang'
export const WAITING = 'waiting opponent'
export const CHAT = 'chat'
