export const INIT = 'init'
export const STARTED = 'started'
export const CHOOSE_1 = 'choose your lang'
export const CHOOSE_2 = 'choose preference lang'
export const WAITING = 'waiting opponent'
export const CHAT = 'chat'
export const ASK = 'ask if user wants to change his lang'
export const CONFIRM = 'leave or not'
